<?php

declare(strict_types=1);

namespace Marko\Vite\Exceptions;

use Marko\Core\Exceptions\MarkoException;

class ManifestNotFoundException extends MarkoException
{
    public static function forPath(
        string $manifestPath,
    ): self {
        return new self(
            message: "Vite manifest file was not found at '$manifestPath'",
            context: "While loading Vite manifest '$manifestPath'",
            suggestion: 'Run your Vite production build or update the configured manifest path.',
        );
    }

    public static function invalidJson(
        string $manifestPath,
        string $reason,
    ): self {
        return new self(
            message: "Vite manifest file at '$manifestPath' is invalid: $reason",
            context: "While decoding Vite manifest '$manifestPath'",
            suggestion: 'Ensure the manifest file contains valid JSON generated by Vite.',
        );
    }
}
