<?php

declare(strict_types=1);

namespace Marko\DevAi\Rendering;

use Marko\DevAi\ValueObject\GuidelinesContent;

readonly class ClaudeMdRenderer
{
    /**
     * @param array{projectName?: string} $input
     */
    public function render(array $input = []): GuidelinesContent
    {
        $body = "<!-- Generated by marko/devai. Do not edit manually. Re-run `marko devai:update` to regenerate. -->\n";
        $body .= "@AGENTS.md\n\n";
        $body .= "# Claude Code Specific Instructions\n\n";
        $body .= "## MCP Tools\n\n";
        $body .= "The `marko-mcp` server provides these tools:\n";
        $body .= "- `search_docs` — search Marko documentation\n";
        $body .= "- `list_modules` / `list_commands` / `list_routes` — explore the project\n";
        $body .= "- `find_event_observers` / `find_plugins_targeting` — inverse-index queries\n";
        $body .= "- `resolve_preference` / `resolve_template` — resolve framework references\n";
        $body .= "- `validate_module` — run consistency checks on a module\n";
        $body .= "- `check_config_key` / `get_config_schema` — validate config usage\n";
        $body .= "- `app_info` / `last_error` / `read_log_entries` / `query_database` / `run_console_command` — runtime introspection\n\n";
        $body .= "## LSP Server\n\n";
        $body .= "The `marko-lsp` server provides:\n";
        $body .= "- Config key completion + goto + diagnostics\n";
        $body .= "- Template name resolution for `module::template` syntax\n";
        $body .= "- Translation key completion + goto\n";
        $body .= "- Marko attribute parameter completion\n";
        $body .= "- Inverse-index code lenses (observers, plugins)\n\n";
        $body .= "## Skills\n\n";
        $body .= "Available Marko skills are in `.claude/skills/`. They cover common Marko workflows like creating modules, drivers, and service contracts.\n\n";
        $body .= "## Plan Mode\n\n";
        $body .= "For multi-file changes, use `hcf:plan-create` to scaffold a plan, then `hcf:plan-orchestrate` to execute autonomously.\n";

        return new GuidelinesContent(body: $body, filename: 'CLAUDE.md');
    }
}
